package generator_test

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/forgego/forge/cli/commands/generation"
	"github.com/forgego/forge/cli/core"
	codegen "github.com/forgego/forge/codegen"
	"github.com/forgego/forge/db/migrate"
	migratecore "github.com/forgego/forge/db/migrate/core"
)

// The fixtures under testdata/dsl define the schema DSL contract that
// docs-site/docs/models.md documents: supported/ holds every form generation
// reads, unsupported/ holds forms that --strict must reject.
var (
	supportedDSL   = filepath.Join("testdata", "dsl", "supported")
	unsupportedDSL = filepath.Join("testdata", "dsl", "unsupported")
)

// copyFixture copies a fixture package's files into a fresh directory.
func copyFixture(t *testing.T, fixture string) string {
	t.Helper()
	dir := t.TempDir()
	entries, err := os.ReadDir(fixture)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		data, err := os.ReadFile(filepath.Join(fixture, entry.Name()))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, entry.Name()), data, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func generateFixture(t *testing.T, dir string) {
	t.Helper()
	gen := codegen.NewGenerator(dir, dir).SetGenerateAPI(true)
	if err := gen.Generate(); err != nil {
		t.Fatalf("generate %s: %v", dir, err)
	}
	if diagnostics := gen.Diagnostics(); len(diagnostics) != 0 {
		t.Fatalf("supported fixture produced diagnostics: %v", diagnostics)
	}
}

func readGenerated(t *testing.T, dir string) map[string][]byte {
	t.Helper()
	files := make(map[string][]byte)
	for _, name := range []string{"gen.go", "api_gen.go"} {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		files[name] = data
	}
	return files
}

// TestSupportedDSLGenerationIsDeterministic generates the supported fixture
// twice in one directory and once in another, and requires byte-identical
// output while files the user owns in that directory stay untouched.
func TestSupportedDSLGenerationIsDeterministic(t *testing.T) {
	dir := copyFixture(t, supportedDSL)
	userFiles := map[string][]byte{
		"models.go":   nil,
		"helpers.go":  []byte("package blog\n\n// Greeting is user-owned code next to the generated files.\nfunc Greeting() string { return \"hello\" }\n"),
		"README.txt":  []byte("user notes\n"),
		"gen_test.go": []byte("package blog\n"),
	}
	for name, data := range userFiles {
		if data == nil {
			continue
		}
		if err := os.WriteFile(filepath.Join(dir, name), data, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	models, err := os.ReadFile(filepath.Join(dir, "models.go"))
	if err != nil {
		t.Fatal(err)
	}
	userFiles["models.go"] = models

	generateFixture(t, dir)
	first := readGenerated(t, dir)
	generateFixture(t, dir)
	second := readGenerated(t, dir)
	other := copyFixture(t, supportedDSL)
	generateFixture(t, other)
	third := readGenerated(t, other)

	for name, data := range first {
		if !bytes.Equal(data, second[name]) {
			t.Errorf("%s changed when regenerated from identical input", name)
		}
		if !bytes.Equal(data, third[name]) {
			t.Errorf("%s differs between two directories with identical input", name)
		}
		if !bytes.HasPrefix(data, []byte("// Code generated by forge. DO NOT EDIT.\n")) {
			t.Errorf("%s lacks the generated-code header", name)
		}
	}
	for name, want := range userFiles {
		got, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("user-owned %s: %v", name, err)
		}
		if !bytes.Equal(got, want) {
			t.Errorf("user-owned %s was modified by generation", name)
		}
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, entry := range entries {
		names = append(names, entry.Name())
	}
	if got, want := strings.Join(names, ","), "README.txt,api_gen.go,gen.go,gen_test.go,helpers.go,models.go"; got != want {
		t.Errorf("directory holds %s, want %s (no stray backup or temp files)", got, want)
	}
}

// wantMarkers returns the fixture's `// want: <text>` markers keyed by line.
func wantMarkers(t *testing.T, file string) map[int]string {
	t.Helper()
	data, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}
	markers := make(map[int]string)
	for i, line := range strings.Split(string(data), "\n") {
		if _, text, ok := strings.Cut(line, "// want: "); ok {
			markers[i+1] = strings.TrimSpace(text)
		}
	}
	if len(markers) == 0 {
		t.Fatalf("%s has no want markers", file)
	}
	return markers
}

// TestUnsupportedDSLDiagnosticsAreSourceLocated checks that each unsupported
// expression yields exactly one diagnostic at its own line.
func TestUnsupportedDSLDiagnosticsAreSourceLocated(t *testing.T) {
	file := filepath.Join(unsupportedDSL, "models.go")
	markers := wantMarkers(t, file)
	parser := codegen.NewASTParser()
	if _, err := parser.ParseDirectory(unsupportedDSL); err != nil {
		t.Fatal(err)
	}
	got := make(map[int]string)
	for _, diagnostic := range parser.Diagnostics() {
		if _, dup := got[diagnostic.Line]; dup {
			t.Errorf("more than one diagnostic on line %d", diagnostic.Line)
		}
		got[diagnostic.Line] = diagnostic.Message
		if filepath.Base(diagnostic.File) != "models.go" || diagnostic.Column == 0 {
			t.Errorf("diagnostic not source-located: %s", diagnostic)
		}
	}
	for line, want := range markers {
		message, ok := got[line]
		if !ok {
			t.Errorf("line %d: no diagnostic, want %q", line, want)
			continue
		}
		if !strings.Contains(message, want) {
			t.Errorf("line %d: diagnostic %q, want substring %q", line, message, want)
		}
	}
	for line, message := range got {
		if _, ok := markers[line]; !ok {
			t.Errorf("unexpected diagnostic at line %d: %s", line, message)
		}
	}
}

// runGenerateCommand runs `forge generate` the way the CLI does and returns
// what it printed to stderr.
func runGenerateCommand(t *testing.T, dir string, strict bool) (string, error) {
	t.Helper()
	command := generation.NewGenerateCommand().Definition()
	args := []string{"--models", dir, "--output", dir}
	if strict {
		args = append(args, "--strict")
	}
	if err := command.ParseFlags(args); err != nil {
		t.Fatal(err)
	}
	read, write, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	original := os.Stderr
	os.Stderr = write
	runErr := generation.NewGenerateCommand().Execute(&core.Context{Cmd: command}, nil)
	_ = write.Close()
	os.Stderr = original
	output, err := io.ReadAll(read)
	_ = read.Close()
	if err != nil {
		t.Fatal(err)
	}
	return string(output), runErr
}

// TestStrictRejectsUnsupportedDSL runs `forge generate --strict` against the
// unsupported fixture: it must fail, print file:line:column for every marked
// expression, and write nothing. The strict run on the supported fixture passes.
func TestStrictRejectsUnsupportedDSL(t *testing.T) {
	dir := copyFixture(t, unsupportedDSL)
	markers := wantMarkers(t, filepath.Join(dir, "models.go"))
	output, err := runGenerateCommand(t, dir, true)
	if err == nil {
		t.Fatal("strict generation accepted the unsupported fixture")
	}
	if !strings.Contains(err.Error(), fmt.Sprintf("found %d model expressions", len(markers))) {
		t.Errorf("error %q does not count %d expressions", err, len(markers))
	}
	for line, want := range markers {
		pattern := regexp.MustCompile(regexp.QuoteMeta(filepath.Join(dir, "models.go")) + fmt.Sprintf(`:%d:\d+: Article\.\w+: .*`, line) + regexp.QuoteMeta(want))
		if !pattern.MatchString(output) {
			t.Errorf("stderr lacks a located diagnostic for line %d (%q):\n%s", line, want, output)
		}
	}
	if _, statErr := os.Stat(filepath.Join(dir, "gen.go")); !os.IsNotExist(statErr) {
		t.Errorf("strict failure wrote gen.go (stat err %v)", statErr)
	}

	supported := copyFixture(t, supportedDSL)
	if output, err := runGenerateCommand(t, supported, true); err != nil {
		t.Fatalf("strict generation rejected the supported fixture: %v\n%s", err, output)
	}
}

// TestSupportedDSLCompiles builds and vets the generated fixture as a consumer
// module that depends on this checkout through a replace directive.
func TestSupportedDSLCompiles(t *testing.T) {
	if testing.Short() {
		t.Skip("compiles a generated module with the go tool")
	}
	root, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	module := t.TempDir()
	pkg := filepath.Join(module, "blog")
	if err := os.MkdirAll(pkg, 0o755); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(supportedDSL, "models.go"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkg, "models.go"), data, 0o644); err != nil {
		t.Fatal(err)
	}
	generateFixture(t, pkg)
	goMod := fmt.Sprintf("module example.com/dslfixture\n\ngo 1.26.0\n\nrequire github.com/forgego/forge v0.0.0\n\nreplace github.com/forgego/forge => %s\n", root)
	if err := os.WriteFile(filepath.Join(module, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	sum, err := os.ReadFile(filepath.Join(root, "go.sum"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(module, "go.sum"), sum, 0o644); err != nil {
		t.Fatal(err)
	}
	for _, args := range [][]string{{"build", "-mod=mod", "./..."}, {"vet", "-mod=mod", "./..."}} {
		cmd := exec.Command("go", args...)
		cmd.Dir = module
		cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=")
		if output, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("go %s on the generated fixture failed: %v\n%s", strings.Join(args, " "), err, output)
		}
	}
}

// makeFixtureMigrations runs makemigrations for the supported fixture.
func makeFixtureMigrations(t *testing.T, driver migratecore.Driver) (string, string) {
	t.Helper()
	dir := t.TempDir()
	gen, err := migrate.NewGeneratorForDriver(supportedDSL, dir, driver)
	if err != nil {
		t.Fatal(err)
	}
	if err := gen.GenerateMigrations("initial"); err != nil {
		t.Fatal(err)
	}
	up, err := os.ReadFile(filepath.Join(dir, "000001_initial.up.sql"))
	if err != nil {
		t.Fatal(err)
	}
	return dir, string(up)
}

// TestSupportedDSLMigrationSQLMatchesSchema checks that the schema facts the
// fixture declares appear in the migration makemigrations writes for it, that
// the output is deterministic, and that regenerating writes nothing new.
//
// Column types are pinned to what the builder emits today for the functional
// constructors (see docs-site/docs/models.md). Changing one alters the DDL of
// existing projects and must ship with an upgrade note.
func TestSupportedDSLMigrationSQLMatchesSchema(t *testing.T) {
	dir, up := makeFixtureMigrations(t, migratecore.DriverPostgreSQL)

	wantColumns := map[string][]string{
		"blog_authors": {
			`"id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY`,
			`"username" TEXT NOT NULL UNIQUE`,
			`"email" TEXT NOT NULL UNIQUE`,
			`"website" TEXT,`,
			`"external_ref" TEXT,`,
			`"bio" TEXT,`,
			`"is_active" BOOLEAN DEFAULT TRUE`,
			`"login_count" INTEGER DEFAULT 0`,
			`"reputation" DOUBLE PRECISION DEFAULT 1.500000`,
			`"ratio" REAL,`,
			`"balance" DOUBLE PRECISION DEFAULT 0`,
			`"settings" BYTEA,`,
			`"avatar" BYTEA,`,
			`"birth_date" TIMESTAMP,`,
			`"created_at" TIMESTAMP DEFAULT now() NOT NULL`,
			`"updated_at" TIMESTAMP DEFAULT now()`,
		},
		"blog_posts": {
			`"id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY`,
			`"title" TEXT NOT NULL,`,
			`"slug" TEXT NOT NULL,`,
			`"status" TEXT NOT NULL DEFAULT 'draft'`,
			`"author_id" BIGINT NOT NULL,`,
			`"word_count" INTEGER DEFAULT 0`,
		},
		"blog_profiles": {
			`"id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY`,
			`"author_id" BIGINT NOT NULL UNIQUE`,
			`"display_name" TEXT`,
		},
	}
	for table, columns := range wantColumns {
		start := strings.Index(up, "CREATE TABLE IF NOT EXISTS "+table+" (")
		if start < 0 {
			t.Fatalf("no CREATE TABLE for %s in:\n%s", table, up)
		}
		body := up[start:]
		body = body[:strings.Index(body, ");")+2]
		if got := strings.Count(body, "\n    \""); got != len(columns) {
			t.Errorf("%s has %d columns, want %d:\n%s", table, got, len(columns), body)
		}
		for _, column := range columns {
			if !strings.Contains(body, column) {
				t.Errorf("%s lacks %s:\n%s", table, column, body)
			}
		}
	}
	for _, statement := range []string{
		`ALTER TABLE blog_posts ADD CONSTRAINT fk_blog_posts_author_id FOREIGN KEY ("author_id") REFERENCES blog_authors (id) ON DELETE CASCADE ON UPDATE NO ACTION;`,
		`ALTER TABLE blog_profiles ADD CONSTRAINT fk_blog_profiles_author_id FOREIGN KEY ("author_id") REFERENCES blog_authors (id) ON DELETE CASCADE ON UPDATE NO ACTION;`,
		`CREATE INDEX IF NOT EXISTS blog_posts_status_idx ON blog_posts ("status");`,
		`ALTER TABLE blog_posts ADD CONSTRAINT blog_posts_word_count_nonnegative CHECK (word_count >= 0);`,
		`ALTER TABLE blog_posts ADD CONSTRAINT blog_posts_author_slug_key UNIQUE ("author_id", "slug");`,
	} {
		if !strings.Contains(up, statement) {
			t.Errorf("migration lacks %s", statement)
		}
	}

	for i := 0; i < 5; i++ {
		if _, again := makeFixtureMigrations(t, migratecore.DriverPostgreSQL); again != up {
			t.Fatalf("makemigrations output differs between runs from identical input")
		}
	}

	gen, err := migrate.NewGeneratorForDriver(supportedDSL, dir, migratecore.DriverPostgreSQL)
	if err != nil {
		t.Fatal(err)
	}
	if err := gen.GenerateMigrations("noop"); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		var names []string
		for _, entry := range entries {
			names = append(names, entry.Name())
		}
		t.Fatalf("regenerating an unchanged model wrote a migration: %v", names)
	}
}
